name: Normal KSU

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [legacy, current]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing kernel sources
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
            rm -rf android_kernel_xiaomi_sm6125
          fi
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-22.2
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.0
          fi
          cp build.sh android_kernel_xiaomi_sm6125/
          chmod +x ./android_kernel_xiaomi_sm6125/build.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_sm6125/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_BLXX
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_BLXX
          fi
          cd ..

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "legacy" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-15/' AnyKernel3/anykernel.sh
          elif [[ "${{ matrix.build-type }}" == "current" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
          fi
          sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
          sed -i 's/device.name2=sweetin/device.name2=ginkgo/' AnyKernel3/anykernel.sh
          sed -i 's/sweet (sm6150)/ginkgo (sm6125)/g' AnyKernel3/banner

      - name: Pack kernel with AnyKernel3
        run: |
          ZIPNAME="perf-neon-ginkgo-weekly-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}
          path: |
            *.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded zips
        run: ls -lah artifacts

      - name: Timestamp
        id: ts
        run: |
          FANCYDATE=$(date +'%Y/%m/%d')
          echo "FANCYDATE=$FANCYDATE" >> $GITHUB_OUTPUT

      - name: Create Release and Upload builds
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: kernel-weekly-${{ needs.build.outputs.timestamp }}
          name: Weekly - ${{ steps.ts.outputs.FANCYDATE }}
          draft: false
          prerelease: false
          body: |
            > [!NOTE]   
            > - The current builds support Android 11 to 16, meanwhile legacy builds support Android 11 to 15.
            > - This build have KernelSU integration with backslashxx's KernelSU.   
            > - KernelSU latest manager for backslashxx's KernelSU can be found in [here](https://github.com/backslashxx/KernelSU/releases) or in [here](https://t.me/kowsu_build).    
               
            > [!CAUTION]   
            > - Always backup your boot & dtbo image first before proceeding!   
          files: |
            artifacts/legacy/*.zip
            artifacts/current/*.zip
          overwrite_files: true
