name: Testing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [current]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing to compile (${{ matrix.build-type }})
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
            rm -rf android_kernel_xiaomi_sm6125
          fi
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125 --depth=1 -b lineage-23.0
          cp build.sh android_kernel_xiaomi_sm6125/
          chmod +x ./android_kernel_xiaomi_sm6125/build.sh

      - name: Compile the kernel (${{ matrix.build-type }})
        run: |
          cd android_kernel_xiaomi_sm6125/
          echo "Starting to compile..."
          ./build.sh trinket-perf_defconfig xiaomi-trinket.config ginkgo.config --ksu=KSU_BLXX
          cd ..

      - name: List build out images (${{ matrix.build-type }})
        run: |
          ls -lahZ android_kernel_xiaomi_sm6125/out/arch/arm64/boot/

      - name: Preparing AnyKernel3 (${{ matrix.build-type }})
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
          cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
          sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
          sed -i 's/device.name2=sweetin/device.name2=ginkgo/' AnyKernel3/anykernel.sh

      - name: Zip kernel contents (${{ matrix.build-type }})
        run: |
          ZIPNAME="aosp-perf-neon-${{ matrix.build-type }}-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}-sweet.zip"
          cd AnyKernel3
          zip -rq9 "../$ZIPNAME" ./*
          cd ..

      - name: Upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.build-type }}-zip
          path: |
            *.zip
